### ISSUE TITLE
Observação

### ISSUE THREAD

**Issue by Evaldo-comp** [marcelomoreira291/Avaliacao_02#1]
https://github.com/marcelomoreira291/Avaliacao_02/blob/5ea6de4f44d782331abda0c21e7f9f10a21e1639/Quest%C3%A3o%207.py#L5

O código gera uma lista de inteiros, mas a questão pede uma lista de listas , como no exemplo abaixo:
`[ [1, 2, 3], [4, 5, 6], [7, 8, 9] ] # lista formada por três listas`

**Comment by marcelomoreira291** [comment]
Entendi.
